language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

env:
  - FEATURES=""
  - FEATURES=native_lib

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true

script:
  - cargo build --features "$FEATURES" --verbose
  - cargo test --features "$FEATURES" --verbose

  - cargo doc --verbose
  - cp .travis/index.html target/doc;

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ -z "$FEATURES" ]; then
      export DEPLOY=1;
    else
      export DEPLOY=0;
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: target/doc
  on:
    branch: master
    rust: stable
    condition: "$DEPLOY = 1"
