language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true

script:
  - cargo build --verbose
  - cargo test --verbose

  - cargo doc
  - cp .travis/index.html target/doc;

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: target/doc
  on:
    branch: master
    rust: stable
