language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - FEATURES=""
  - FEATURES=native_lib

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true

before_install:
  - if [ -n "$FEATURES" ]; then
      sudo apt-get install -y libwayland-client0;
    fi

script:
  - cargo build --features "$FEATURES" --verbose
  - cargo test --features "$FEATURES" --verbose

  - cargo doc --verbose
  - cp .travis/index.html target/doc;

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: target/doc
  on:
    branch: master
    rust: stable
    condition: "-z $FEATURES"
