[package]
name = "wl-clipboard-rs"
version = "0.8.0" # remember to update html_root_url
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
description = "Access to the Wayland clipboard for terminal and other window-less applications."
edition = "2021"
license = "MIT/Apache-2.0"

readme = "README.md"
documentation = "https://docs.rs/wl-clipboard-rs"
repository = "https://github.com/YaLTeR/wl-clipboard-rs"
keywords = ["wayland", "clipboard"]
categories = ["command-line-utilities"]

[workspace]
members = [".", "wl-clipboard-rs-tools"]

[dependencies]
derive-new = "0.5.9"
libc = "0.2.148"
log = "0.4.20"
nix = "0.26.4"
os_pipe = { version = "1.1.4", features = ["io_safety"] }
tempfile = "3.8.0"
thiserror = "1"
tree_magic_mini = "3.0.3"
wayland-backend = "0.3.2"
wayland-client = "0.31.1"
wayland-protocols = { version = "0.31.0", features = ["client"] }
wayland-protocols-wlr = { version = "0.2.0", features = ["client"] }

[dev-dependencies]
wayland-server = "0.31.0"
wayland-protocols = { version = "0.31.0", features = ["server"] }
wayland-protocols-wlr = { version = "0.2.0", features = ["server"] }
proptest = "1.3.1"
proptest-derive = "0.4.0"

[features]
# Link to libwayland-client.so instead of using the Rust implementation.
native_lib = ["wayland-backend/client_system", "wayland-backend/server_system"]

dlopen = ["native_lib", "wayland-backend/dlopen", "wayland-backend/dlopen"]
