[package]
name = "wl-clipboard-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[[bin]]
name = "wl-paste"
path = "src/wl_paste.rs"

# [profile.dev]
# panic = "abort"

[dependencies]
env_logger = "*"
derive-new = "*"
derive_more = "*"
log = "*"
os_pipe = "*"
structopt = {version = "*", features = ["wrap_help"]}
wayland-client = {git = "https://github.com/Smithay/wayland-rs.git"}
wayland-commons = {git = "https://github.com/Smithay/wayland-rs.git"}

[dependencies.wayland-protocols]
git = "https://github.com/Smithay/wayland-rs.git"
features = ["client", "unstable_protocols"]

[dependencies.wayland-sys]
git = "https://github.com/Smithay/wayland-rs.git"
features = ["client"]
optional = true

[build-dependencies]
wayland-scanner = {git = "https://github.com/Smithay/wayland-rs.git"}

[features]
# Link to libwayland-client.so instead of using the Rust implementation.
native_lib = [
    "wayland-sys",
    "wayland-client/native_lib",
    "wayland-commons/native_lib",
    "wayland-protocols/native_lib",
]
