[package]
name = "wl-clipboard-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"

[[bin]]
name = "wl-paste"
path = "src/wl_paste.rs"

[[bin]]
name = "wl-copy"
path = "src/wl_copy.rs"

# [profile.dev]
# panic = "abort"

[dependencies]
env_logger = "*"
derive-new = "*"
derive_more = "*"
libc = "*"
log = "*"
nix = "*"
os_pipe = "*"
tempfile = "*"
structopt = {version = "*", features = ["wrap_help"]}
wayland-client = "*"
wayland-commons = "*"

[dependencies.wayland-protocols]
version = "*"
features = ["client", "unstable_protocols"]

[dependencies.wayland-sys]
version = "*"
features = ["client"]
optional = true

[build-dependencies]
wayland-scanner = "*"

[features]
# Link to libwayland-client.so instead of using the Rust implementation.
native_lib = [
    "wayland-client/native_lib",
    "wayland-commons/native_lib",
    "wayland-protocols/native_client",
    "wayland-sys",
]
