[package]
name = "wl-clipboard-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

readme = "README.md"
repository = "https://github.com/YaLTeR/wl-clipboard-rs"

[badges]
travis-ci = { repository = "YaLTeR/wl-clipboard-rs" }

[[bin]]
name = "wl-paste"
path = "src/bin/wl_paste.rs"

[[bin]]
name = "wl-copy"
path = "src/bin/wl_copy.rs"

# [profile.dev]
# panic = "abort"

[dependencies]
derive-new = "*"
derive_more = "*"
env_logger = "*"
exitfailure = "*"
failure = "*"
libc = "*"
log = "*"
mime_guess = "2.0.0-alpha"
nix = "*"
os_pipe = "*"
structopt = {version = "*", features = ["wrap_help"]}
tempfile = "*"
tree_magic = "*"
wayland-client = "*"
wayland-commons = "*"

[dependencies.wayland-protocols]
version = "*"
features = ["client", "unstable_protocols"]

[dependencies.wayland-sys]
version = "*"
features = ["client"]
optional = true

[build-dependencies]
wayland-scanner = "*"

[dev-dependencies]
wayland-server = "*"

[dev-dependencies.wayland-protocols]
version = "*"
features = ["server", "unstable_protocols"]

[features]
# Link to libwayland-client.so instead of using the Rust implementation.
native_lib = [
    "wayland-client/native_lib",
    "wayland-commons/native_lib",
    "wayland-protocols/native_client",
    "wayland-protocols/native_server",
    "wayland-server/native_lib",
    "wayland-sys",
]

dlopen = [
    "native_lib",
    "wayland-client/dlopen",
    "wayland-server/dlopen",
]
