[package]
name = "wl-clipboard-rs-tools"
version = "0.5.0"
edition = "2018"

[dependencies]
wl-clipboard-rs = { path = "../" }
anyhow = "1.0.56"
libc = "0.2.121"
log = "0.4.14"
mime_guess = "2.0.4"
nix = "0.23.1"
stderrlog = "0.5.1"
structopt = { version = "0.3.26", features = ["wrap_help"] }

[features]
# Link to libwayland-client.so instead of using the Rust implementation.
native_lib = [
    "wl-clipboard-rs/native_lib",
]

dlopen = [
    "wl-clipboard-rs/dlopen",
]
