[package]
name = "wl-clipboard-rs-tools"
version = "0.8.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
description = "Terminal utilities for accessing the Wayland clipboard."
edition = "2018"
license = "MIT/Apache-2.0"

readme = "README.md"
documentation = "https://docs.rs/wl-clipboard-rs"
repository = "https://github.com/YaLTeR/wl-clipboard-rs"
keywords = ["wayland", "clipboard"]
categories = ["command-line-utilities"]

[dependencies]
wl-clipboard-rs = { path = "../", version = "0.8.0" }
anyhow = "1.0.71"
libc = "0.2.146"
log = "0.4.19"
mime_guess = "2.0.4"
nix = "0.26.2"
stderrlog = "0.5.4"
structopt = { version = "0.3.26", features = ["wrap_help"] }

[features]
# Link to libwayland-client.so instead of using the Rust implementation.
native_lib = [
    "wl-clipboard-rs/native_lib",
]

dlopen = [
    "wl-clipboard-rs/dlopen",
]
