name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        rust: [stable, beta]
        features: ['', dlopen]

    name: ${{ matrix.rust }} - ${{ matrix.features }}
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --features=${{ matrix.features }}

      - name: Set up XDG_RUNTIME_DIR
        run: |
          mkdir .runtime
          echo "XDG_RUNTIME_DIR=$PWD/.runtime" >> $GITHUB_ENV

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --features=${{ matrix.features }}

      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --features=${{ matrix.features }}

      - name: Copy documentation index
        run: cp doc/index.html target/doc/

      - name: Deploy documentation
        if: >
          matrix.rust == 'stable' &&
          matrix.features == '' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc

  clippy:
    name: clippy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all

  rustfmt:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly
          components: rustfmt

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
